CREATE DATABASE IF NOT EXISTS ProblemDB;

USE ProblemDB;

CREATE TABLE IF NOT EXISTS PROBLEMS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    problem_name VARCHAR(255) NOT NULL,
    topic VARCHAR(100) NOT NULL,
    difficulty VARCHAR(20) NOT NULL,
    file_path VARCHAR(500) NOT NULL
);
